---
title: "Ribo-Seq"
author: "Sascha Stutz, Peter Meili, Philipp Osterwalder"
date: "3 Oktober 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Genome-Wide Analysis in Vivo of Translation with Nucleotide Resolution Using Ribosome Profiling

## Overview

In [1](http://science.sciencemag.org/content/324/5924/218) a ribosome-profiling strategy is presented that is based on the deep sequencing of ribosome-protected mRNA fragments and enables genome-wide investigation of translation with subcodon resolution. A ribosome-profiling strategy that is based on the deep sequencing of ribosome-protected mRNA fragments is used and enables genome-wide investigation of translation with subcodon resolution. 


# or

# Ribosome Profiling

Ribosome profiling, or Ribo-Seq (also named Ribosome footprinting), is an adaptation  to work with next generation sequencing that uses specialized messenger RNA (mRNA) sequencing to determine which mRNAs are being actively translated. It produces a “global snapshot” of all the ribosomes active in a cell at a particular moment, known as a translatome. Consequently, this enables identifying the location of translation start sites, the complement of translated ORFs in a cell or tissue, the distribution of ribosomes on a messenger RNA, and the speed of translating ribosomes.

## Linking Technologies to Applications to Statistics 



## github usernames

- pmeili
- stusas

#### References:
[1: http://science.sciencemag.org/content/324/5924/218](http://science.sciencemag.org/content/324/5924/218)

